import type { Config } from "tailwindcss";
export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "var(--ink)",
        paper: "var(--paper)",
        muted: "var(--muted)",
        accent: "var(--accent)",
        surface: "var(--surface)",
        line: "var(--line)",
        "brand-red": "var(--brand-red)",
        "on-dark": "var(--on-dark)",
        "dark-muted": "var(--dark-muted)",
        "on-accent": "var(--on-accent)",
        night: "var(--night)",
        "display-accent": "var(--display-accent)",
      },
      fontFamily: {
        sans: ["var(--font-body)", "sans-serif"],
        arabic: ["var(--font-arabic)", "var(--font-body)", "sans-serif"],
      },
      fontSize: {
        ...Object.fromEntries(
          [
            "subheading",
            "kicker",
            "eyebrow",
            "intro",
            "micro",
            "word",
            "ticker",
            "admin-heading",
            "badge",
            "tiny",
            "offer",
            "nav-mobile",
            "detail",
            "cta",
            "quote-mark",
            "quote",
            "symbol",
            "admin",
            "note-small",
            "nano",
            "word-mobile",
            "offer-mobile",
            "nav-small",
            "admin-mobile",
            "stamp",
            "service",
          ].map((name) => [name, `var(--text-${name})`]),
        ),
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        heading: "var(--heading)",
        display: "var(--display)",
        "display-ar": "var(--display-ar)",
        label: "var(--text-label)",
        caption: "var(--text-caption)",
      },
      borderRadius: { lg: "var(--radius)" },
    },
  },
  plugins: [],
} satisfies Config;
